spring.application.name=UrlShortener
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=openbase

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.schema=classpath*:src/main/resources/schema.sql
spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

logging.level.org.springframework.transaction=DEBUG
logging.level.org.springframework.jdbc=DEBUG

server.port=8080
